### ISSUE TITLE
Open property window link on click on bookmark icon

### ISSUE THREAD

**Issue by GreenItSolutions** [mignz/GlobalTab#1]
Hi,
Thanks for this very good extension.
As an enhancement, is it possible to add a link in each bookmark icon to automatically open firefox property bookmark or Chrome Modify bookmark ?

Thanks in advance,
Bertrand

**Comment by mignz** [comment]
Hi, you're welcome. First, my primary objective with this extension is to keep it extremely fast and uncluttered so I might be against adding new "stuff". I didn't quite understand what you're asking though,

**Comment by GreenItSolutions** [comment]
Thanks for your fast response.
I always add an description and some tags on my bookmarks. All I hope is to can click on the boomark icon to open default property window, like right click on bookmark link in the bookmark pane

**Comment by mignz** [comment]
Ah, I see what you mean. In this case I'd have to implement my own context menu (overhead). You actually gave me an idea to add an arrow to the right side of the bookmarks with a drop down menu to edit the name and URL of the bookmark, maybe more.

**Comment by GreenItSolutions** [comment]
Yep, that's it. Hope i can help you to test because  i'm not developer and can't code.

**Comment by mignz** [comment]
This will be implemented on version 1.2.0. I'll be releasing it soon.

**Comment by GreenItSolutions** [comment]
Hi,
Thanks a lot for this enhancement. It works great on firefox and chrome.
