### ISSUE TITLE
Display bookmark spacer as lines

### ISSUE THREAD

**Issue by GreenItSolutions** [mignz/GlobalTab#2]
In firefox, spacers are represent as arrow. Can you replace this with a line
Thanks in advance.
I add a screenshot for best explanation.
![kazam_screenshot_00001](https://user-images.githubusercontent.com/15212645/38218282-7de19c30-36d1-11e8-851d-1b5a98319ba4.png)

**Comment by mignz** [comment]
Now supported on v1.2.0.

**Comment by GreenItSolutions** [comment]
Hi,
Thanks. It works.
