### ISSUE TITLE
Subfolders

### ISSUE THREAD

**Issue by GreenItSolutions** [mignz/GlobalTab#3]
Subfolders in Firefox and Chrome are not correctly represent.
Each subfolder is represent with an undefined icon and link to extension url like "moz-extension://ea38f2f2-2c42-461e-b8df-602e3ed290be/undefined".
Is it possible to replace the icon with a folder icon and if you click on, can expand and indent the sublinks
i give you a screenshot to best understand.
![kazam_screenshot_00004](https://user-images.githubusercontent.com/15212645/38218706-00ba95ca-36d3-11e8-911f-8a7f00709874.png)

**Comment by mignz** [comment]
Subfolders are not supported.
